---
- name: Configure web server on AWS EC2
  hosts: webserver
  become: yes
  tasks:
    - name: Install nginx
      yum:
        name: nginx
        state: latest

    - name: Start nginx
      systemd:
        name: nginx
        enabled: yes
        state: started

    - name: Add index.html
      copy:
        content: |
          <html>
          <head><title>Hello World</title></head>
          <body><h1>Hello World!</h1></body>
          </html>
        dest: /usr/share/nginx/html/index.html

    - name: Set up nginx to redirect HTTP to HTTPS
      blockinfile:
        path: /etc/nginx/nginx.conf
        block: |
          server {
            listen 80 default_server;
            server_name _;
            return 301 https://$host$request_uri;
          }
        marker: "# {mark} ANSIBLE MANAGED BLOCK"

    - name: Configure HTTPS on nginx
      blockinfile:
        path: /etc/nginx/nginx.conf
        block: |
          server {
            listen 443 ssl default_server;
            server_name _;
            ssl_certificate /etc/ssl/certs/nginx-selfsigned.crt;
            ssl_certificate_key /etc/ssl/private/nginx-selfsigned.key;
            location / {
              root /usr/share/nginx/html;
              index index.html index.htm;
            }
          }
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
