name: CI for Nginx Server Configuration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby for Serverspec
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ansible
        gem install serverspec rake

    - name: Run Serverspec Tests
      run: |
        cd tests
        rake spec

    - name: Deploy with Ansible if tests pass
      if: success()
      run: |
        cd ansible
        ansible-playbook -i inventory.ini playbook.yml
