name: CI for Nginx Server Configuration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ../tests/Gemfile

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Ruby for Serverspec
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'

    - name: Install Serverspec
      run: |
        sudo gem install serverspec

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ansible
        sudo gem install serverspec rake
        sudo gem install bundler
        sudo bundle install

    - name: Check gem installation
      run: sudo gem list serverspec

    - name: Set GEM_PATH
      run: sudo echo "GEM_PATH=$(gem env gemdir)" >> $GITHUB_ENV
    
    - name: Print Gem Environment
      run: sudo gem env
    
    - name: Run Serverspec Tests
      run: |
        cd tests
        bundle exec rake spec --trace

    - name: Deploy with Ansible if tests pass
      if: success()
      run: |
        cd ansible
        ansible-playbook -i inventory.ini playbook.yml
